### ISSUE TITLE
Question regrading the UVO Dataset 

### ISSUE THREAD

**Issue by YScheung** [dulucas/UVO_Challenge#11]
Firstly, Thank You for your amazing work.  

There’s a question I would like to ask regarding the UVO Dataset. I would like to work on the dense dataset. Through the download link in the homepage of the challenge, I could access ‘UVO_video_train_dense.json’, ‘UVO_video_val_dense.json’ and  ‘UVO_video_test_dense.json’ that specify the video ids of the train, validation and test datasets. However, I’m unsure how I could obtain the videos. Could you please guide me on how I could obtain the original and annotated videos ?

Many thanks

**Comment by dulucas** [comment]
Try this?
 https://drive.google.com/drive/folders/1fOhEdHqrp_6D_tBsrR9hazDLYV2Sw1XC

**Comment by YScheung** [comment]
Thank You for your reply. I have downloaded uvo_videos_dense.zip. However, only original videos are available in the folder, while annotated / segmented videos are missing ...

**Comment by dulucas** [comment]
Yes, the annotation should be stored in [here](https://drive.google.com/drive/folders/1eOIaOdh9dKX-uiPKxe5GG83IsX7pbI0G) in [coco format](https://cocodataset.org/#format-data).

**Comment by YScheung** [comment]
Thank You for your reply. In the README for the Dense dataset, it's mentioned that we could find annotation information of the videos from uvo_json["annotations"] . However, I'm sorry that I'm still unable to find the json file that stores the annotation information of the videos in coco format in the google drive. Could you please let me know the json file name ?


Many thanks

**Comment by YScheung** [comment]
Got it. Thank You very much for your help

**Comment by LuciferZap** [comment]
The google drive link shows "Can't access item", could you share another links? thank you.
