### ISSUE TITLE
wgts links failed

### ISSUE THREAD

**Issue by lluo-Desktop** [dulucas/UVO_Challenge#13]
Hi！
     Sorry to bother! The links to download weights failed.
     Can you offer model weights ? I'm seeking for object detection model.
      Thank you!
                                    BR!
                                     George.

**Comment by dulucas** [comment]
Hi, thx for your interests! I deleted the weights because there is no enough space in my google drive(even for the emails...), do you know if there are any other free cloud space that I can put my models in?

**Comment by dulucas** [comment]
And if you focus more on AP rather than AR, I would recommand other models from mmdetection. Because our model is more AR oriented and can produce much more false positives during the prediction.

**Comment by lluo-Desktop** [comment]
> And if you focus more on AP rather than AR, I would recommand other models from mmdetection. Because our model is more AR oriented and can produce much more false positives during the prediction.

Hi
  Thanks for reply.
  1) You can check pCloud  / Box  cloud space.
  2) Thanks for your suggest！ AR is also important for us, becuase we are trying to find and cluster new categories.

**Comment by LengZhuo0831** [comment]
Hello!
Could you share me the segmentation model weight finetuned on UVO? (The links fail) 
Thank you very much!
Leng Zhuo.

**Comment by dulucas** [comment]
Hi, all, I just uploaded all the models to my google drive and updated the links in the README, you should be able to download them now. BUT, please do it quick as the models have occupied almost all my drive storage and might affect my daily usage(receiving emails etc), so I might need to remove them in near future...😂 sorry for the inconvenience

**Comment by lluo-Desktop** [comment]
Got it! 
Thx for your help and patience！

**Comment by whut2962575697** [comment]
The link failed again, could you updated again, thank you.

**Comment by whut2962575697** [comment]
> Got it! Thx for your help and patience！

Do you have the checkpoint file, can you share me, thank you

**Comment by lluo-Desktop** [comment]
> > Got it! Thx for your help and patience！
> 
> Do you have the checkpoint file, can you share me, thank you

Hi, I'm sorry that I can not upload any file from my PC.  It's locked for any file delivering.

**Comment by dulucas** [comment]
the links are renewed and available. You can download the models using the links in README
